package composition.flower;

public enum FlowerName {
	ROSE, TULIP, CARNATION, DANDELION, GERANIUM, LILY, IRIS, CHRYSANTHEMUM, 
	VIOLET, PETUNIA, ORCHID, GLADIOLUS, ASTER, LILAC, LILY_OF_THE_VALLEY;
}
