
public enum BookType {
	
	SADDLE_STITCH_BINDING, PUR_BINDING, HARDCOVER, SINGER_SEWN_BINDING, 
	SECTION_SEWN_BINDING, COPTIC_STITCH_BINDING, SPIRAL_BINDING, INTER_SCREW_BINDING,  
	JAPANESE_BINDING, SOLANDER_BOXES;

}
