package State;

public enum DistrictEnum {
	BARANAVICHY(RegionEnum.BREST_REGION), BREST(RegionEnum.BREST_REGION), BYAROZA(RegionEnum.BREST_REGION),
	DRAHICHYN(RegionEnum.BREST_REGION), HANTSAVICHY(RegionEnum.BREST_REGION), IVANAVA(RegionEnum.BREST_REGION),
	IVATSEVICHY(RegionEnum.BREST_REGION), KAMENETS(RegionEnum.BREST_REGION), KOBRYN(RegionEnum.BREST_REGION),
	LUNINETS(RegionEnum.BREST_REGION), LYAKHAVICHY(RegionEnum.BREST_REGION), MALARYTA(RegionEnum.BREST_REGION),
	PINSK(RegionEnum.BREST_REGION), PRUZHANY(RegionEnum.BREST_REGION), STOLIN(RegionEnum.BREST_REGION), ZHABINKA(RegionEnum.BREST_REGION),
	
	BESHANKOVICHY(RegionEnum.VITEBSK_REGION), BRASLAW(RegionEnum.VITEBSK_REGION), CHASHNIKI(RegionEnum.VITEBSK_REGION), 
	DOKSHYTSY(RegionEnum.VITEBSK_REGION), DUBROŬNA(RegionEnum.VITEBSK_REGION), HARADOK(RegionEnum.VITEBSK_REGION), 
	HLYBOKAYE(RegionEnum.VITEBSK_REGION), LEPIEL(RegionEnum.VITEBSK_REGION), LIOZNA(RegionEnum.VITEBSK_REGION), 
	MYORY(RegionEnum.VITEBSK_REGION), ORSHA(RegionEnum.VITEBSK_REGION), PASTAVY(RegionEnum.VITEBSK_REGION), 
	POLOTSK(RegionEnum.VITEBSK_REGION), RASONY(RegionEnum.VITEBSK_REGION), SHARKAWSHCHYNA(RegionEnum.VITEBSK_REGION), 
	SHUMILINA(RegionEnum.VITEBSK_REGION), SYANNO(RegionEnum.VITEBSK_REGION), TALACHYN(RegionEnum.VITEBSK_REGION), 
	USHACHY(RegionEnum.VITEBSK_REGION), VITEBSK(RegionEnum.VITEBSK_REGION), VERKHNYADZVINSK(RegionEnum.VITEBSK_REGION),
	
	AKCIABRSKI(RegionEnum.GOMEL_REGION), BRAHIN(RegionEnum.GOMEL_REGION), BUDA_KASHALYOVA(RegionEnum.GOMEL_REGION),
	CHACHERSK(RegionEnum.GOMEL_REGION), DOBRUSH(RegionEnum.GOMEL_REGION), GOMEL(RegionEnum.GOMEL_REGION), 
	KALINKAVICHY(RegionEnum.GOMEL_REGION), KARMA(RegionEnum.GOMEL_REGION), KHOINIKI(RegionEnum.GOMEL_REGION),
	LYELCHYTSY(RegionEnum.GOMEL_REGION), LOYEW(RegionEnum.GOMEL_REGION), MAZYR(RegionEnum.GOMEL_REGION), 
	NAROULIA(RegionEnum.GOMEL_REGION), PIETRYKAW(RegionEnum.GOMEL_REGION), RAHACHOW(RegionEnum.GOMEL_REGION), 
	RECHYTSA(RegionEnum.GOMEL_REGION), SVIETLAHORSK(RegionEnum.GOMEL_REGION), VIETKA(RegionEnum.GOMEL_REGION), YEL_SK(RegionEnum.GOMEL_REGION),
	ZHLOBIN(RegionEnum.GOMEL_REGION), ZHYTKAVICHY(RegionEnum.GOMEL_REGION),
	
	ASHMYANY(RegionEnum.GRODNO_REGION), ASTRAVYETS(RegionEnum.GRODNO_REGION), BYERASTAVITSA(RegionEnum.GRODNO_REGION), 
	DZYATLAVA(RegionEnum.GRODNO_REGION), GRODNO(RegionEnum.GRODNO_REGION), IWYE(RegionEnum.GRODNO_REGION), 
	KARELICHY(RegionEnum.GRODNO_REGION), LIDA(RegionEnum.GRODNO_REGION), MASTY(RegionEnum.GRODNO_REGION), 
	NAVAHRUDAK(RegionEnum.GRODNO_REGION), SHCHUCHYN(RegionEnum.GRODNO_REGION), SLONIM(RegionEnum.GRODNO_REGION), 
	SMARHON(RegionEnum.GRODNO_REGION), SVISLACH(RegionEnum.GRODNO_REGION), VAWKAVYSK(RegionEnum.GRODNO_REGION), 
	VORANAVA(RegionEnum.GRODNO_REGION), ZELVA(RegionEnum.GRODNO_REGION),
	
	BARYSAW(RegionEnum.MINSK_REGION), BYERAZINO(RegionEnum.MINSK_REGION), CHERVYEN(RegionEnum.MINSK_REGION), 
	DZYARZHYNSK(RegionEnum.MINSK_REGION), KAPYL(RegionEnum.MINSK_REGION), KLETSK(RegionEnum.MINSK_REGION), 
	KRUPKI(RegionEnum.MINSK_REGION), LAHOYSK(RegionEnum.MINSK_REGION), LYUBAN(RegionEnum.MINSK_REGION), 
	MALADZYECHNA(RegionEnum.MINSK_REGION), MINSK(RegionEnum.MINSK_REGION), MYADZYEL(RegionEnum.MINSK_REGION), 
	NESVIZH(RegionEnum.MINSK_REGION), PUCHAVIČY(RegionEnum.MINSK_REGION), SALIHORSK(RegionEnum.MINSK_REGION), 
	SLUTSK(RegionEnum.MINSK_REGION), SMALYAVICHY(RegionEnum.MINSK_REGION), STARYYA_DAROHI(RegionEnum.MINSK_REGION), 
	STOWBTSY(RegionEnum.MINSK_REGION), UZDA(RegionEnum.MINSK_REGION), VALOZHYN(RegionEnum.MINSK_REGION), VILEYKA(RegionEnum.MINSK_REGION),
	
	ASIPOVICHY(RegionEnum.MOGILEV_REGION), BABRUYSK(RegionEnum.MOGILEV_REGION), BYALYNICHY(RegionEnum.MOGILEV_REGION), 
	BYKHAW(RegionEnum.MOGILEV_REGION), CHAVUSY(RegionEnum.MOGILEV_REGION), CHERYKAW(RegionEnum.MOGILEV_REGION), DRYBIN(RegionEnum.MOGILEV_REGION), 
	HLUSK(RegionEnum.MOGILEV_REGION), HORKI(RegionEnum.MOGILEV_REGION), KASTSYUKOVICHY(RegionEnum.MOGILEV_REGION), 
	KHOTSIMSK(RegionEnum.MOGILEV_REGION), KIRAWSK(RegionEnum.MOGILEV_REGION), KLICHAW(RegionEnum.MOGILEV_REGION), 
	KLIMAVICHY(RegionEnum.MOGILEV_REGION), KRASNAPOLLE(RegionEnum.MOGILEV_REGION), KRUHLAYE(RegionEnum.MOGILEV_REGION), 
	KRYCHAW(RegionEnum.MOGILEV_REGION), MOGILEV(RegionEnum.MOGILEV_REGION), MSTSISLAW(RegionEnum.MOGILEV_REGION), SHKLOW(RegionEnum.MOGILEV_REGION), 
	SLAWHARAD(RegionEnum.MOGILEV_REGION);
	
	RegionEnum regionEnum;

	private DistrictEnum(RegionEnum regionEnum) {
		this.regionEnum = regionEnum;
	}

	public RegionEnum getRegionEnum() {
		return regionEnum;
	}

	public void setRegionEnum(RegionEnum regionEnum) {
		this.regionEnum = regionEnum;
	}	
}
